[toolchain]

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "./mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.localnet]
devalshield_vault = "BppKFtdQqyLtn6PZtME52UrXDUyi67Lwn68UaXBUSrtc"

[programs.devnet]
devalshield_vault = "BppKFtdQqyLtn6PZtME52UrXDUyi67Lwn68UaXBUSrtc"
