[package]
name = "devalshield-vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
mpl-core = { version = "1.0", features = ["anchor"] }
spl-stake-pool = { version = "0.8", features = ["no-entrypoint"] }
